export const FETCH_CHAPTER_REQUEST = "FETCH_CHAPTER_REQUEST";
export const FETCH_CHAPTER_FAILURE = "FETCH_CHAPTER_FAILURE";
export const FETCH_CHAPTER_SUCCESS = "FETCH_CHAPTER_SUCCESS";

export const FETCH_LINKS_REQUEST = "FETCH_LINKS_REQUEST";
export const FETCH_LINKS_FAILURE = "FETCH_LINKS_FAILURE";
export const FETCH_LINKS_SUCCESS = "FETCH_LINKS_SUCCESS";
